### ISSUE TITLE
Title frontend validation throwing an error

### ISSUE THREAD

**Issue by prasath95** [codinginflow/MERN-course#4]
To check the Title's validation in the below lines, throwing an error

```
 <Form.Control.Feedback type="invalid">
          {errors.title?.message} // if I comment on this, the error not throwing 
 </Form.Control.Feedback>
```

the error messages

```
./src/components/addNoteDialog.tsx 123:18
Module parse failed: Unexpected token (123:18)
You may need an appropriate loader to handle this file type.
|       columnNumber: 25
|     }
>   }, errors.title?.message)), /*#__PURE__*/React.createElement(Form.Group, {
|     className: "mb-3",
|     __self: _this,
```

**Comment by prasath95** [comment]
This happened because of the lower version of the react script, so just updated and now it's working fine, check the [question here](https://stackoverflow.com/questions/76495619/you-may-need-an-appropriate-loader-to-handle-this-file-type-react-hook-form-def/76495719?noredirect=1#comment134878276_76495719), 

`npm install --save --save-exact react-scripts@5.0.1`

**Comment by codinginflow** [comment]
Glad you figured it out!
